# Generated by Django 3.1.5 on 2021-01-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20210110_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='slug',
            field=models.CharField(default=False, max_length=64),
            preserve_default=False,
        ),
    ]
