# Generated by Django 3.1.5 on 2021-01-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_station_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
