# Generated by Django 3.1.5 on 2021-01-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20210111_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'verbose_name': 'Chart', 'verbose_name_plural': 'Charts'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
        migrations.AlterField(
            model_name='chart',
            name='added_date',
            field=models.DateField(unique=True),
        ),
    ]
