# Generated by Django 3.1.5 on 2021-01-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_auto_20210111_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='added_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together={('station', 'added_date')},
        ),
    ]
