# Generated by Django 3.1.5 on 2021-01-11 15:27

import charts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_auto_20210111_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='station',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='logo_path',
            field=models.ImageField(blank=True, null=True, upload_to=charts.utils.UploadTo('logo')),
        ),
    ]
