# Generated by Django 3.1.5 on 2021-01-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0009_auto_20210111_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
